export const DEFAULT_FLOATING_X = 300;
export const DEFAULT_FLOATING_Y = 150;
export const DEFAULT_FLOATING_HEIGHT = 350;
export const DEFAULT_FLOATING_WIDTH = 350;
export const DEFAULT_FLOATING_MAX_HEIGHT = 300;
export const DEFAULT_FLOATING_MAX_WIDTH = 480;
